eduSite/eduSite/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from quiz.views.api_views import *

# participant_router = routers.SimpleRouter()
# author_router = routers.SimpleRouter()
#
# participant_router.register(r'quizzes', QuizPartialViewSet)
# participant_router.register(r'questions', QuestionPartialViewSet)
# participant_router.register(r'answers', AnswerPartialViewSet)
# participant_router.register(r'quiz/(?P<connection_code>.+)/results', QuizResultViewSet, basename='QuizResult')
# participant_router.register(r'result/(?P<result>.+)/question-results', QuestionResultViewSet)
#
# # participant_router.register(r'quiz/(?P<connection_code>.+)/question-ids', QuizQuestionsIdListVewSet)
# participant_router.register(r'quiz/question-ids', QuizQuestionsIdListVewSet)
#
# author_router.register(r'quizzes', QuizViewSet)
# author_router.register(r'quiz/(?P<quiz>.+)/questions', QuestionViewSet, basename='Question')
# author_router.register(r'quiz/(?P<quiz>.+)/question/(?P<question>.+)/answers', AnswerViewSet, basename='Answer')


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/participant/', include(participant_router.urls)),
    # path('api/author/', include(author_router.urls)),
    path('', include('quiz.urls.urls'))
]

eduSite/quiz/urls/urls.py
from django.urls import path, include
from rest_framework import routers

from quiz.urls import author_urls, participant_urls
from quiz.urls.author_urls import author_router
from quiz.urls.participant_urls import participant_router
from quiz.views.page_views import *

urlpatterns = [
    path('', index, name='home'),
    path('quiz/<int:quiz_pk>/<int:question_order>/', quiz_constructor, name='quiz_constructor'),
    path('quiz/<int:quiz_pk>/<int:question_order>/del/', delete_question),
    path('quiz/<int:quiz_pk>/publish/', publish_quiz),
    path('quiz-preview/', quiz_preview, name='quiz_preview'),
    path('api/participant/', include(participant_router.urls)),
    path('api/participant/', include(participant_urls.urlpatterns)),
    path('api/author/', include(author_router.urls)),
    path('api/author/', include(author_urls.urlpatterns)),
    # path('quiz-solving/<slug:connection_code>/', enter_name, name='name'),
    path('quiz-solving/<slug:connection_code>/<int:question_number>/', quiz_solving, name='quiz'),
    path('quiz-results/<str:room_name>/', room, name='room'),
]

eduSite/quiz/models.py
from django.db import models


class Quiz(models.Model):
    connection_code = models.SlugField(max_length=50, unique=True, db_index=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return str(self.connection_code)

class Question(models.Model):
    text = models.CharField(max_length=300)
    # order = models.IntegerField()
    score = models.IntegerField(default=1)
    # correct_answers = models.ManyToManyField('Answer', related_name='correct_answers', blank=True)
    quiz = models.ForeignKey('Quiz', related_name='questions', on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Answer(models.Model):
    text = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey('Question', related_name='answers', on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class QuizResult(models.Model):
    participant = models.CharField(max_length=100)
    quiz = models.ForeignKey('Quiz', related_name='results', on_delete=models.CASCADE)


class QuestionResult(models.Model):
    chosen_answers = models.ManyToManyField('Answer', related_name='chosen_answers', blank=True)
    is_correct = models.BooleanField()
    question = models.ForeignKey('Question', related_name='results', on_delete=models.CASCADE)
    quiz_result = models.ForeignKey('QuizResult', related_name='question_results', on_delete=models.CASCADE)

eduSite/quiz/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Quiz, Answer, Question


class QuizConnectionForm(forms.Form):
    connection_code = forms.SlugField(
        max_length=50,
        widget=forms.TextInput(attrs={
            'placeholder': 'Введи его сюда',
            'form': 'quiz-connection'
        })
    )
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': 'Введи имя сюда:',
            'form': 'quiz-connection'
        })
    )

    def clean_connection_code(self):
        connection_code = self.cleaned_data['connection_code']
        if not Quiz.objects.filter(connection_code=connection_code).exists():
            raise ValidationError('Quiz с таким кодом присоединения не существует')
        return connection_code


class QuestionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Question
        fields = ['text']
        widgets = {
            'text': forms.TextInput(attrs={
                'name': 'answer-text',
                'class': 'new-question-text',
                'placeholder': 'Введите текст вопроса...'
            }),
        }

class AnswerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Answer
        fields = ['text', 'is_correct']
        widgets = {
            'text': forms.TextInput(attrs={
                'name': 'answer-text',
                'class': 'new-answer-text',
                'placeholder': 'Введите ответ...'
            }),
            'is_correct': forms.CheckboxInput()
        }
class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['connection_code']
        widgets = {
            'connection_code': forms.TextInput(attrs={
                'id': 'create-quiz-code'
            })
        }

class AnswerInlineFormset(forms.BaseInlineFormSet):
    deletion_widget = forms.CheckboxInput(attrs={
        'class': 'mark-for-deletion'
    })

class DeleteQuestionForm(forms.Form):
    pass

class PublishQuizForm(forms.Form):
    pass

eduSite/quiz/views.py
from django.shortcuts import render, get_object_or_404
from rest_framework import viewsets, mixins
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .models import *
from .serializers import *
from rest_framework.views import APIView
from rest_framework import generics


class QuizViewSet(
    mixins.CreateModelMixin,
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    # mixins.ListModelMixin,
    GenericViewSet
):
    queryset = Quiz.objects.all()
    serializer_class = QuizSerializer


class QuestionViewSet(viewsets.ModelViewSet):
    # queryset = Question.objects.all()
    serializer_class = QuestionSerializer

    def get_queryset(self):
        quiz = self.kwargs['quiz']
        quiz_instance = get_object_or_404(Quiz, pk=quiz)
        return quiz_instance.questions.all()


class AnswerViewSet(viewsets.ModelViewSet):
    # queryset = Answer.objects.all()
    serializer_class = AnswerSerializer

    def get_queryset(self):
        quiz = self.kwargs['quiz']
        question = self.kwargs['question']
        get_object_or_404(Quiz, pk=quiz)
        question_instance = get_object_or_404(Question, pk=question)
        return question_instance.answers.all()


class AnswerPartialViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Answer.objects.all()
    serializer_class = AnswerPartialSerializer


class QuestionPartialViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionPartialSerializer


class QuizPartialViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Quiz.objects.all()
    serializer_class = QuizPartialSerializer

    lookup_field = 'connection_code'


class QuestionResultViewSet(mixins.CreateModelMixin,
                            mixins.RetrieveModelMixin,
                            mixins.DestroyModelMixin,
                            mixins.ListModelMixin,
                            GenericViewSet):
    queryset = QuestionResult.objects.all()
    serializer_class = QuestionResultSerializer


class QuizResultViewSet(mixins.CreateModelMixin,
                        mixins.RetrieveModelMixin,
                        mixins.DestroyModelMixin,
                        mixins.ListModelMixin,
                        GenericViewSet):
    # queryset = QuizResult.objects.all()
    serializer_class = QuizResultSerializer
    def get_queryset(self):
        quiz = get_object_or_404(Quiz, connection_code=self.kwargs['connection_code'])
        return quiz.results.all()

eduSite/quiz/views/page_views.py
import django.forms
from django.forms import inlineformset_factory, forms
from django.forms.formsets import DELETION_FIELD_NAME
from django.http import HttpResponseNotFound
from django.shortcuts import render, get_object_or_404, redirect
from ..forms import QuizForm, DeleteQuestionForm, QuestionForm, AnswerForm, QuizConnectionForm, AnswerInlineFormset
from ..models import *

def index(request):
    if request.method == 'POST':
        if 'quiz-connect' in request.POST:
            quiz_connection_form = QuizConnectionForm(request.POST)
            quiz_creation_form = QuizForm()
            if quiz_connection_form.is_valid():
                try:
                    response = redirect(f'quiz-solving/{quiz_connection_form.cleaned_data["connection_code"]}/1')
                    response.set_cookie('name', quiz_connection_form.cleaned_data['name'])
                    return response
                except:
                    quiz_connection_form.add_error(None, 'Что-то пошло не так')
        if 'quiz-create' in request.POST:
            quiz_creation_form = QuizForm(request.POST)
            quiz_connection_form = QuizConnectionForm()
            if quiz_creation_form.is_valid():
                try:
                    new_quiz = quiz_creation_form.save()
                    return redirect(f'/quiz/{new_quiz.pk}/1/')
                except:
                    quiz_creation_form.add_error(None, 'Ошибка создания Quiz')
    else:
        if 'name' in request.COOKIES.keys():
            quiz_connection_form = QuizConnectionForm({'name': request.COOKIES['name']})
        else:
            quiz_connection_form = QuizConnectionForm()
        quiz_creation_form = QuizForm()

    context = {
        'quiz_creation_form': quiz_creation_form,
        'quiz_connection_form': quiz_connection_form,
        'title': 'Quizzz'
    }

    return render(request, 'quiz/index.html', context=context)

def quiz_constructor(request, quiz_pk, question_order):
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    questions = quiz.questions.all()
    questions_count = len(questions)
    del_question = DeleteQuestionForm()
    if question_order > questions_count + 1 or question_order <= 0:
        return HttpResponseNotFound()
    elif question_order <= questions_count:
        AnswerFormSet = inlineformset_factory(
            Question,
            Answer,
            form=AnswerForm,
            formset=AnswerInlineFormset,
            fields=['text', 'is_correct'],
            extra=1
        )
        if request.method == 'POST':
            print(request.POST)
            question = questions[question_order - 1]
            question_form = QuestionForm(request.POST, instance=question)
            answers_formset = AnswerFormSet(request.POST, instance=question)
            if question_form.is_valid():
                question_form.save()
            if answers_formset.is_valid():
                answers_formset.save()
            return redirect(f'/quiz/{quiz_pk}/{question_order}')

        question = questions[question_order - 1]
        question_form = QuestionForm(instance=question)
        answers_formset = AnswerFormSet(instance=question)
    else:
        AnswerFormSet = inlineformset_factory(
            Question,
            Answer,
            form=AnswerForm,
            formset=AnswerInlineFormset,
            fields=['text', 'is_correct'],
            extra=4
        )
        question = Question(quiz_id=quiz_pk)
        if request.method == 'POST':
            AnswerFormSet.extra = 0
            question_form = QuestionForm(request.POST, instance=question)
            answers_formset = AnswerFormSet(request.POST, instance=question)
            if question_form.is_valid():
                question = question_form.save()
            if answers_formset.is_valid():
                answers_formset.save()
            return redirect(f'/quiz/{quiz_pk}/{question_order + 1}/')
        question_form = QuestionForm(instance=question)
        answers_formset = AnswerFormSet(instance=question)

    context = {
        'question_form': question_form,
        'answers_formset': answers_formset,
        'del_question': del_question,
        'quiz_pk': quiz_pk,
        'questions_count': questions_count,
        'question_order': question_order,
        'prev': question_order - 1,
        'next': question_order + 1
    }
    return render(request, 'quiz/quiz-constructor.html', context=context)

def delete_question(request, quiz_pk, question_order):
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    questions = quiz.questions.all()
    questions_count = len(questions)
    if question_order > questions_count:
        return HttpResponseNotFound()
    if request.method == 'POST':
        questions[question_order - 1].delete()
        return redirect(f'/quiz/{quiz_pk}/{question_order}')

def publish_quiz(request, quiz_pk):
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    if quiz.questions.all().exists():
        quiz.is_published = True
        quiz.save()
        return redirect(f'/quiz-results/{quiz_pk}')
    else:
        return redirect(f'/quiz/{quiz_pk}/1')

def quiz_preview(request):
    context = {
        'title': 'Предпросмотр Quiz'
    }

    return render(request, 'quiz/quiz-preview.html', context=context)



def quiz_solving(request, connection_code, question_number):
    quiz = get_object_or_404(Quiz, connection_code=connection_code)
    questions = quiz.questions.all()
    question = questions[question_number - 1]
    context = {
        'title': f'Quiz: {connection_code}',
        'name': request.COOKIES['name'],
        'quiz': quiz,
        'question': question,
        'question_number': question_number,
        'questions_count': len(questions),
        'answers': question.answers.all()
    }
    if len(question.answers.filter(is_correct=True)) == 1:
        return render(request, 'quiz/single-choice-solving.html', context=context)
    else:
        return render(request, 'quiz/multiple-choice-solving.html', context=context)
def room(request, room_name):
    return render(request, 'quiz/results.html', {
        'title': f'Results: {Quiz.objects.get(pk=room_name).connection_code}',
        'room_name': room_name
    })

eduSite/quiz/templates/quiz/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/css/style.css' %}">
    <meta charset="utf-8">
    <title>{{title}}</title>
</head>
<body>
    <header>
        <div class="nav-container">
            <nav class="header-nav">
                <a href="{% url 'home' %}" class="main-logo">
                  <img src="{% static 'quiz/img/logo-2.svg' %}" class="nav-item logo">
                </a>
                <a href="#" class="nav-item create-test">Создать тест</a>
                <a href="#" class="nav-item info">Как это работает?</a>
                <a href="#" class="nav-item contacts">Контакты</a>
            </nav>
            <button class="connection-code hidden">
                Код присоединения
            </button>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <div class="footer-content">
            <img class="footer-logo" src="{% static 'quiz/img/logo.svg' %}">
            <div class="social-networks">
                <a href="#"><img class="social-network" src="{% static 'quiz/img/telegram.svg' %}"></a>
                <a href="#"><img class="social-network" src="{% static 'quiz/img/instagram.svg' %}"></a>
            </div>
        </div>
    </footer>
</body>
{% block scripts %}
{% endblock %}
</html>

eduSite/quiz/templates/quiz/enter-name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Enter Name</title>
</head>
<body>
<h2>Введите имя</h2>
<input id="name-input" type="text" size="100"><br>
<input id="name-submit" type="button" value="Enter">
</body>
<script>
    btn = document.querySelector('#name-submit');
    btn.onclick = (evt) => {
        evt.preventDefault()
        console.log(window.location.pathname)
        window.location.pathname += document.querySelector('#name-input').value + '/1/' ;
    }
</script>
</html>

eduSite/quiz/templates/quiz/index.html
{% extends 'quiz/base.html' %}
{% load static %}

{% block content %}
<div>
    <form id="quiz-creation" action="" method="post">
        {% csrf_token %}
        {{quiz_creation_form.connection_code}}<!--<input type="text" name="connection_code" id="create-quiz-code" maxlength="50" required="">-->
        <!--Стандартное отображение ошибок валидации django. При успешной загрузке javascript его нужно спрятать, включив валидацию на js
        (код присоединения содержит только латинские буквы, цифры, подчёркивания, дефисы, не повторяется(такого кода не существует, если на
        запрос GET http://127.0.0.1:8000/api/participant/quizzes/{код}/ получен ответ {"detail":"Not found."})-->
        {{quiz_creation_form.errors}}<!--<ul class="errorlist"><li>connection_code<ul class="errorlist"><li>{текст ошибки}</li></ul></li></ul>-->
        <button type="submit" name="quiz-create">Погнали!</button>
    </form>
</div>
<div class="connection-wrapper">
    <div class="connection">
        <img src="./img//connection-code-pic.png" width="348px">
        <div>
            <h2>Есть код присоединения?</h2>
            <p>Скорей беги проходить тест</p>
        </div>
        <form id="quiz-connection" action="" method="post">
            {% csrf_token %}
            <!--Для элементов формы указан атрибут form, так что их можно выносить за пределы тега <form> без последствий-->
            <!--<input type="text" name="connection_code" placeholder="Введи его сюда" form="quiz-connection" maxlength="50" required="" id="id_connection_code">-->
            {{quiz_connection_form.connection_code}}
            <!--<input type="text" name="name" placeholder="Введи имя сюда:" form="quiz-connection" maxlength="100" required="" id="id_name">-->
            {{quiz_connection_form.name}}
            <!--Аналогично предыдущему списку ошибок валидации-->
            {{quiz_connection_form.errors}}
            <button form="quiz-connection" type="submit" name="quiz-connect" id="code-submit"></button>
        </form>
    </div>
</div>
<script>
    //btn = document.querySelector('#code-submit');
    //btn.onclick = (evt) => {
    //    evt.preventDefault()
    //    window.location.pathname = '/quiz-solving/' + document.querySelector('#code-input').value + '/';
    //}
</script>
{% endblock %}

eduSite/quiz/templates/quiz/multiple-choice-solving.html
{% extends 'quiz/base.html' %}
{% load static %}

{% block content %}
<body>
<div>
    <h2>{{question.text}}</h2>
    <div class="answers">
        {% for answer in answers %}
        <div>
          <p>{{answer.text}}</p><input type="checkbox" value="{{answer.pk}}">
        </div>

        {% endfor %}
      <button id="send">Отправить</button>
    </div>
</div>
</body>
<script>
    const quizSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/quiz/'
            + '{{quiz.pk}}'
            + '/'
        );
    chosenAnswers = [];
    document.querySelector('#send').onclick = function test(evt) {
        checkboxes = document.querySelectorAll('input[type="checkbox"]:checked');
        checkboxes.forEach(c => {
            chosenAnswers.push(parseInt(c.value));
        });
        quizSocket.send(JSON.stringify({
            'name': '{{name}}',
            'question_pk': {{question.pk}},
            'question_text': '{{question.text}}',
            'question_number': {{question_number}},
            'chosen_answers': chosenAnswers
        }))
        if (parseInt({{question_number}}) + 1 <= {{questions_count}}) {
            window.location.pathname = 'quiz-solving/{{quiz.connection_code}}/' + (parseInt({{question_number}}) + 1) + '/'
        }
        else {
            window.location.pathname = ''
        }
    };
</script>
{% endblock %}

eduSite/quiz/templates/quiz/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>глапрлаполапола</title>
</head>
<body>
вановпролспрлвпрлав
</body>
</html>

eduSite/quiz/templates/quiz/quiz-constructor.html
{% extends 'quiz/base.html' %}
{% load static %}

{% block content %}
<div class="quiz-constructor-container">
    <div class="phone-wrapper">
        <div class="phone-preview">
            <output class="question-text" name="question-text" form="question-form">
                В каком году родился Иван Грозный?
            </output>
            <div class="answers">
                <output class="answer" id="answer-output-1" form="question-form">
                    1530
                </output>
                <output class="answer" id="answer-output-2" form="question-form">
                    1529
                </output>
                <output class="answer" id="answer-output-3" form="question-form">
                    1528
                </output>
                <output class="answer" id="answer-output-4" form="question-form">
                    1527
                </output>

            </div>
        </div>
        <div class="flipper creation-flipper">
            <a class="flip-arrow flip-left" href="/quiz/{{quiz_pk}}/{{prev}}"{% if question_order <= 1 %}style="pointer-events: none;"{% endif %}></a>
            <div>
                <span class="current-question">{{question_order}}</span>/<span class="question-count">{{questions_count}}</span>
            </div>
            <a class="flip-arrow flip-right" href="/quiz/{{quiz_pk}}/{{next}}"{% if question_order > questions_count %}style="pointer-events: none;"{% endif %}></a>
        </div>
    </div>
    <!--Нужна валидация - не давать отправлять, пока нет хотя бы двух ответов, из которых хотя бы 1 отмечен-->
    <form action="" method="POST" class="construction-menu" id="question-form" autocomplete="off">
        {% csrf_token %}
        <!--<input type="text" name="text" class="new-question-text" placeholder="Введите текст вопроса..." maxlength="300" required="" id="id_text">-->
        {{question_form.text}}
        {{answers_formset.management_form}}

        <div class="add-answers">
            {% for form in answers_formset %}
            {% csrf_token %}
            <div class="new-answer">
                <!--<input type="text" name="answers-{номер}-text" class="new-answer-text" placeholder="Введите ответ..." maxlength="100" id="id_answers-{номер}-text">-->
                {{form.text}}
                <label class="checkbox-correct-label">
                    <!--<input type="checkbox" name="answers-{номер}-is_correct" id="id_answers-{номер}-is_correct">-->
                    {{form.is_correct}}
                    <span></span>
                </label>
                <!--Чекбокс, отвечающий за удаление сохранённого ответа. Нужно:
                а) сделать красивым и понятным - кастомным, с иконкой ведра или ещё чего
                (вроде вот нужная статья: https://itchief.ru/html-and-css/styling-checkbox-and-radio, в общем, всё как с чекбоксами is_correct выше)
                б) (необязательно, но стоило бы) при успешной загрузке js: в идеале: чекбокс спрятан, при опустошении поля сохранённого ответа
                спрятанный чекбокс отмечается, прячется вся форма, отвечающая за этот ответ. Не в идеале: при нажатии на чекбокс удаления прячется
                 вся форма, отвечающая за этот ответ -->
                <!--<input type="checkbox" name="answers-{номер}-DELETE" class="mark-for-deletion" id="id_answers-{номер}-DELETE">-->
                {{form.DELETE}}
                <!--скрытое техническое поле-->
                {{form.id}}
            </div>
            {% endfor %}
            <!--Кнопка добавления новой формы для ответа. Нужно сделать менее уродской, а лучше - спрятать и автоматически активировать при заполнении всех полей-->
            <button id="add-form" type="button">+</button>
        </div>

        <div class="buttons">
            <button form="q-del" class="button-delete" type="submit">
                Удалить
            </button>
            <button type="submit" class="button-save">
                Сохранить
            </button>
        </div>
        <button form="q-publish" type="submit">
            Перейти к результатам
        </button>
    </form>
    <form id="q-del" action="del/" method="POST">
        {% csrf_token %}
    </form>
    <form id="q-publish" action="/quiz/{{quiz_pk}}/publish/" method="POST">
        {% csrf_token %}
    </form>
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'quiz/js/quiz-constructor.js' %}" type="module"></script>
<script>
    let newAnswer = document.querySelectorAll(".new-answer");
    let container = document.querySelector(".add-answers");
    let addButton = document.querySelector("#add-form");
    let totalForms = document.querySelector("#id_answers-TOTAL_FORMS")
    let formNum = newAnswer.length - 1
    function addForm(e) {
        e.preventDefault();

        let newForm = newAnswer[0].cloneNode(true);
        newForm.querySelector(".new-answer-text").setAttribute('value', '');
        newForm.querySelector(".checkbox-correct-label input").removeAttribute("checked");
        newForm.querySelector(".mark-for-deletion").removeAttribute("checked");
        let formRegex = RegExp(`answers-(\\d){1}-`,'g');

        formNum++;
        newForm.innerHTML = newForm.innerHTML.replace(formRegex, `answers-${formNum}-`);
        container.insertBefore(newForm, addButton);

        totalForms.setAttribute('value', `${formNum+1}`);
}
    addButton.addEventListener('click', addForm)
</script>
{% endblock %}

eduSite/quiz/templates/quiz/quiz-preview.html
{% extends 'quiz/base.html' %}
{% load static %}

{% block content %}
{% endblock %}

eduSite/quiz/templates/quiz/quiz-solving.html
{% extends 'quiz/base.html' %}
{% load static %}

{% block content %}
<body>
<div>
    <h2>{{question.text}}</h2>
    <div class="answers">
        {% for answer in answers %}
        <button value="{{answer.pk}}">
            {{answer.text}}
        </button>
        {% endfor %}
    </div>
</div>
</body>
<script>
    const quizSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/quiz/'
            + '{{quiz.pk}}'
            + '/'
        );
    document.querySelector('.answers').onclick = function test(evt) {
        const target = evt.target;
        if (target.tagName != 'BUTTON') {
            return;
        }
        quizSocket.send(JSON.stringify({
            'name': '{{name}}',
            'question': {{question.pk}},
            'chosen_answers': [target.value]
        }))
        if (parseInt({{question_number}}) + 1 <= {{questions_count}}) {
            window.location.pathname = 'quiz-solving/{{quiz.connection_code}}/' + (parseInt({{question_number}}) + 1) + '/'
        }
        else {
            window.location.pathname = ''
        }
    };
</script>
{% endblock %}

eduSite/quiz/templates/quiz/results.html
{% extends 'quiz/base.html' %}
{% load static %}

{% block content %}
{{ room_name|json_script:"room-name" }}
<script>
    const roomName = JSON.parse(document.getElementById('room-name').textContent);
    const quizSocket = new WebSocket(
        'wss://'
        + window.location.host
        + '/ws/quiz/'
        + roomName
        + '/'
    );

    quizSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        console.log(data)
    };

    quizSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };
</script>
{% endblock %}

eduSite/quiz/templates/quiz/single-choice-solving.html
{% extends 'quiz/base.html' %}
{% load static %}

{% block content %}
<body>
<div>
    <h2>{{question.text}}</h2>
    <div class="answers">
        {% for answer in answers %}
        <button value="{{answer.pk}}">
            {{answer.text}}
        </button>
        {% endfor %}
    </div>
</div>
</body>
<script>
    const quizSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/quiz/'
            + '{{quiz.pk}}'
            + '/'
        );
    document.querySelector('.answers').onclick = function test(evt) {
        const target = evt.target;
        if (target.tagName != 'BUTTON') {
            return;
        }
        quizSocket.send(JSON.stringify({
            'name': '{{name}}',
            'question_pk': {{question.pk}},
            'question_text': '{{question.text}}',
            'question_number': {{question_number}},
            'chosen_answers': [parseInt(target.value)]
        }))
        if (parseInt({{question_number}}) + 1 <= {{questions_count}}) {
            window.location.pathname = 'quiz-solving/{{quiz.connection_code}}/' + (parseInt({{question_number}}) + 1) + '/'
        }
        else {
            window.location.pathname = ''
        }
    };
</script>
{% endblock %}